name: line_chart
description: A simple flutter package to create a custom line chart
version: 1.1.11
repository: https://github.com/lucas-sesti/line_chart

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
