name: line_chart
description: A simple flutter package to create a custom line chart
version: 1.0.1
repository: https://github.com/lucas-sesti/line_chart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
